FROM python:3.14.0a6-bullseye

WORKDIR /usr/src/flexbnb_backend


ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONNUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./Requirements.txt .
RUN pip install -r Requirements.txt

COPY . .